version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
